version: '3.1'

   services:
    wordpress:
        image: wordpress:latest
        ports:
            - "80:80"
        environment:
            WORDPRESS_DB_HOST: <RDS-endpoint>
            WORDPRESS_DB_USER: <DB-username>
            WORDPRESS_DB_PASSWORD: <DB-password>
            WORDPRESS_DB_NAME: <DB-name>
        volumes:
            - wp_data:/var/www/html

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: <DB-root-password>
            MYSQL_DATABASE: <DB-name>
            MYSQL_USER: <DB-username>
            MYSQL_PASSWORD: <DB-password>
        volumes:
            - db_data:/var/lib/mysql

    volumes:
        wp_data:
        db_data:
